### ISSUE TITLE
vslideup and vslidedown are not symmetric 

### ISSUE THREAD

**Issue by solomatnikov** [riscv/riscv-v-spec#304]
vslidedown shifts in 0s

vslideup leaves elements < OFFSET unchanged

**Comment by kasanovic** [comment]
I can see that making vslidedown leave values unchanged might be more useful in more cases.

**Comment by kasanovic** [comment]
The vl can always be adjusted to give the symmetric behavior.  Returning zero of out-of-range indices is consistent with vrgather.

**Comment by solomatnikov** [comment]
then, why not to do the same for vslideup?

**Comment by aswaterman** [comment]
Zeroing the vacated elements for vslideup would add another special case.
Currently, vstart and OFFSET are handled the same as each other, but that
would no longer be the case if the vacated elements were zeroed.

I'm not bothered by the asymmetry, but if we had to make a change, I would
change vslidedown rather than changing vslideup.

**Comment by solomatnikov** [comment]
zeroing for vslidedown is also a special case and is bad for performance because without renaming vslidedown takes the same number of cycles as if vl == VLMAX

**Comment by kasanovic** [comment]
I'm OK with changing vslidedown to not zero past vl-offset.

**Comment by kasanovic** [comment]
Consensus was to leave these instructions as is for now, and to work on code examples to see how they're used.

**Comment by kasanovic** [comment]
I believe there is no motivation to change this.
