### ISSUE TITLE
Optional carry-in for vmadc/vmsbc

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-v-spec#316]
For multi-word integer arithmetic, `v0` is always zero when generating carry out for lowest word, so we need an extra `vmclr.m` to clear that.

```
# Generate carry out for lowest word.
vmclr.m v0
vmadc.vvm   v1, v2, v3, v0 
# Generate carry out for second word.
vmcpy.m v0, v1
vmadc.vvm   v1, v4, v5, v0 
...
```

And we can remove `vmclr.m` if `v0`/carry-in is optional for `vmadc`.

```
# Generate carry out for lowest word.
vmadc.vvm   v1, v2, v3
# Generate carry out for second word.
vmcpy.m v0, v1
vmadc.vvm   v1, v4, v5, v0 
...
```

**Comment by aswaterman** [comment]
The performance impact is probably pretty minor, but I think the change actually simplifies the control logic slightly, so it's probably worth doing.

Right now, these instructions are defined to read the mask unconditionally, and are required to have m=1.  If we were to make this change, we would want to change that behavior to simplify the hardware: they should read the mask only if m=0 (like other mask ops), and should write back unconditionally (like vmerge).  Hence, these instructions would become less of a special case.  We would want to change `vadc` and `vsbc` in addition to `vmadc` and `vmsbc` (but we would disallow `vadc` and `vsbc` when m=1, because in that case they are equivalent to `vadd`/`vsub`.)
