### ISSUE TITLE
How to unpack subfields from segment load?

### ISSUE THREAD

**Issue by edre** [riscv/riscv-v-spec#363]
The section on vector segment load says:

> For segments with heterogeneous-sized fields, software can later unpack fields using additional instructions after the segment load brings the values into the separate vector registers.

I assume this is suggesting using the vector narrowing instructions, but I don't see how those can work here. The segment-load vectors will be striped one element at a time, whereas the narrowing instructions take register groups with striping presumably determined by SLEN. These striping patterns seem incompatible; am I missing something?

For context, I'm playing with a vectorized crypto round function for Chacha20, where each round does a bunch of stuff to 16 32-bit ints, which I have represented as one vector lane each. Since segment load doesn't go past 8 fields, I'm trying to segment-load 8 64-bit fields, then unpack them into 16 32-bit registers. It's not clear to me what instructions would accomplish this.

**Comment by ZPedro** [comment]
Neither I can see how you could unscramble the fields using segment loads and narrowing instructions in your specific case of 16 fields, indeed because it's larger than 8, the limit for NFIELDS*LMUL. I believe the sentence you are quoting instead refers to situation where the structure to load has a shape such as:

    struct heterogeneous
    {
        uint32_t wide;
        uint16_t narrow1;
        uint16_t narrow2;
    }

where sizeof(struct heterogeneous)/sizeof(narrowest field) <= 8.

This same observation led me to propose interleaving/deinterleaving operations in issue #294. In the meantime, your best bet would be to load segments of eight 32-bit elements, and either operate on non-uniform vectors (tricky) or use vrgather to unshuffle them to obtain uniform vectors.

**Comment by edre** [comment]
The workaround I'm using for now is to just have 16 separate strided loads/stores. I assume this would make less efficient use of memory throughput, but I don't really know.

**Comment by kasanovic** [comment]
You can use simple non-narrowing right shifts to extract fields from elements. 

For your chacha20 example, you could use two strided segment loads, each of 8 fields, with stride of 16*32b/8b = 64 bytes.  This would pack the data structures as densely as possible in the registers.

Using a single 8*64b load is possible.  Then use simple right shift to extra high 32b of each 64b word into bottom of 64b element in different vector register.   This will waste half the vector register storage, as you'll only be using the bottom half of each element.

**Comment by edre** [comment]
I'm not sure how I missed the strided segment instructions; that's a much cleaner approach.
I had been looking into a 64-bit segment load, but the bookkeeping around using half of the vector width (especially when odd) was getting daunting.
