### ISSUE TITLE
relationship between max SEW and ELEN

### ISSUE THREAD

**Issue by HanKuanChen** [riscv/riscv-v-spec#452]
In [3.3.1](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#331-vector-standard-element-width-vsew20), it says
```
In the base vector extension, only SEW up to max(XLEN,FLEN) are required to be supported.
```
But why does it not
```
In the base vector extension, only SEW up to ELEN are required to be supported.
```
It seems like we can have a hardware with ELEN 64 but only support max SEW 32. (I know it is weird.)
But in the second case, we cannot have this weird configuration.

**Comment by aswaterman** [comment]
Related to #404.  In that issue, the question is "is SEW permitted to be greater than max(XLEN, FLEN)"?  The answer is, of course, yes.  This issue is asking, "is SEW permitted to be less than max(XLEN, FLEN)?"  IMO, the answer _should_ be yes.

Elsewhere, the spec already says `Platform profiles may set further constraints on these parameters, for example, requiring that ELEN ≥ max(XLEN,FLEN)`.  This seems inconsistent with the sentence @HanKuanChen quoted, so perhaps it's an editing error, and we should remove the ISA constraint and make it a platform constraint.
