### ISSUE TITLE
Opcode of VFMADD and VFMSUB

### ISSUE THREAD

**Issue by rofirrim** [riscv/riscv-v-spec#55]
Hi,

I noticed in the current `inst-table.adoc` that `VFMADD.{S,D.Q}` use the `NMSUB` opcode and `VFMSUB.{S,D,Q}` use the `NMADD` opcode.

I would expect `VFMADD` use the `NMADD` and `VFMSUB` use the `NMSUB` opcode (actually I'd expect them to use `MADD` and `MSUB` respectively but perhaps they are not useable, I didn't check that).

Is this intentional?

Thanks a lot.

**Comment by colinschmidt** [comment]
This is an intentional encoding optimization. Non-destructive 3 input operations take a lot of encoding space so we've packed them in where we could.
The vector FMAs fits into the two unused rounding modes of the scalar FMA opcodes.
Predicated versions are in `MADD` and `MSUB` with `rm` signifying v1.f(101) and v1.t(110)
Non-predicated versions are in `NMADD` and `NMSUB` with `rm` signifying scalar(101) or vector(110) dest.
