### ISSUE TITLE
vlsegff exception behavior

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-v-spec#576]
We should specify what happens when a first-fault segment load encounters an exception partway through a segment.

To keep the HW simple, we should retain the property that first-fault loads behave as similarly to non-first-fault loads as possible.  It should be valid to partially load the segment before resetting vl to the beginning of the segment (for elts >0) or trapping (for elt 0).

For first-fault loads, portable software can't rely on the contents of the vector register past the new vl, anyway, so this won't further constrain code generation.

**Comment by David-Horner** [comment]
Perhaps the pull title is throwing me off - specify vs clarify?
There are two parts to this:
### Clarifying the imprecise nature of loads and their visibility after a ff instruction:
my take is : this is a specific case of the recently accepted more general relaxed load order.
I am in favour of clarification that reinforces the general case and does not imply a special case related to the ff variants.
The general case may need to be explicitly mentioned if the context does not make the distinction specific vs special abundantly clear.
The context does not have any indication that segmented loads in general allow imprecise exceptions.
Thus the note would suggest a special case for the ff variant wrt load order effects.
This same caveat should be mentioned in non-segmented load fault first.
The reason is that, although we have chosen to make vstart user visible, exception handling is done by the EE and can thus can normally hide such warts from the the [casual] user. For ff this is not the case. Thus warts are exposed, specifically that between the new vl and the old vl values are undefined. Tail undisturbed also does not hold in this range. it could be argued that it never held as it is the old vl that controls for the directive. 
I recommend the text for these clarifications emphasize this is but a consequence of the more general case.
### Different behaviour for segmented vs non-segmented ff load?.
>regardless of whether the element index is zero

If this refers to vl of zero, non-segmented load differs:
it does not allow vl to be set to zero.

>Even when an exception is not raised, implementations are permitted to process fewer than vl elements and reduce vl accordingly, but if vstart=0 and vl>0, then at least one element must be processed.
Note | vl is not modified if element 0 raises an exception.
Implementations should not reduce vl and instead set a non-zero vstart value when the fault-only-first instruction takes a trap due to an interrupt.
 
If it refers to vstart then we have different behaviour:
>instead set a **non-zero vstart** value when the fault-only-first instruction takes a trap

I think this may need further explanation?

But in this case, specification vs clarification of behaviour is appropriate.

I hope to create suggested wording when I am back from travel.
