### ISSUE TITLE
Spec clarification on vid.v instruction and destination-source overlap

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-v-spec#579]
Should vid.v raise an illegal instruction exception when masked and when the destination group overlaps v0 ?

**Comment by aswaterman** [comment]
Yes, per https://github.com/riscv/riscv-v-spec/blob/454bf945b2d64cddf2ef85874dad6078145a2e91/v-spec.adoc#53-vector-masking -- "The destination vector register group for a masked vector instruction cannot overlap the source mask register (v0), unless the destination vector register is being written with a mask value (e.g., comparisons) or the scalar result of a reduction. Otherwise, an illegal instruction exception is raised."

**Comment by jrahmeh** [comment]
Thanks
