### ISSUE TITLE
vsetvl instruction decode clarification

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-v-spec#630]
The decode pattern given for the `vsetvl` instruction has the value `0x1000` specified for the penultimate field. Can you explain what this means? I was expecting all zeroes here, which is what it was in the "old" instruction format description.

(I haven't looked at this since everything was converted to the new format a few months ago.)

```
{reg: [
  {bits: 7,  name: 0x57, attr: 'vsetvl'},
  {bits: 5,  name: 'rd', type: 4},
  {bits: 3,  name: 7},
  {bits: 5,  name: 'rs1', type: 4},
  {bits: 5,  name: 'rs2', type: 4},
  {bits: 6,  name: 0x1000},
  {bits: 1,  name: 1},
]}
```

**Comment by aswaterman** [comment]
I have no idea what it means, but it renders as all zeros:

![Screen Shot 2021-02-03 at 3 40 33 PM](https://user-images.githubusercontent.com/1031106/106823676-377ae480-6636-11eb-9eff-985d31f302a8.png)

**Comment by JamesKenneyImperas** [comment]
A stupid question: how do I see the rendered result? It would by nice if the links from the specification could show this instead of the raw form.

**Comment by aswaterman** [comment]
Take a look at the README.  It requires some setup.

**Comment by JamesKenneyImperas** [comment]
ok, thanks.

**Comment by David-Horner** [comment]
Even though it can be generated locally, having a 'properly' rendered pdf
on the site for major updates is as helpful in riscv-v-spec as in
riscv-isa-manual.

My experience has been that I got different renderings. Perhaps due to
slightly different versions of software, perhaps configuration defaults.
But an official  reference would avoid spurious reports of errors AND
provide an authoratative document.

**Comment by JamesKenneyImperas** [comment]
Yes David, I completely agree
