### ISSUE TITLE
slt ops: unsigned comparison should use UIMM instead of IMM

### ISSUE THREAD

**Issue by vbx-glemieux** [riscv/riscv-v-spec#678]
unsigned comparison operators with immediate operands seem to use IMM instead of UIMM:

vmsleu.vi vd, vs2, imm, vm   # Vector-immediate
vmsgtu.vi vd, vs2, imm, vm   # Vector-immediate

is this intentional, or should it be UIMM?

**Comment by aswaterman** [comment]
As with SLTIU in the base ISA, the immediates are sign-extended even though they represent unsigned quantities.

**Comment by ubc-guy** [comment]
now a part of me wants to change the base ISA as well :P

as much as this displeases me, I can understand the rationale. to avoid perception of a typo, should a note be added stating this is done for consistency with base ISA?

**Comment by aswaterman** [comment]
The NOTE immediately below the assembly does make it clear, I think.

**Comment by ubc-guy** [comment]
oops that note stresses my patience due to it's length and intricate content, so I didn't read it carefully. yes, I see now that it mentions "always sign-extended", but doesn't say WHY. this is also a separate concept from the beginning of the note which talks about the lack of a .vi form for vmslt{u}.

there should only be one concept per note, splitting this one up into 2 or more:  (a) omission of vmslt{u}.vi and range limits, (b) 5b sign-extended immediates with implication on values <0, and (c) all of the useless opcode encodings, eg when IMM=0 or 2^SEW (and I recommend that these useless encodings be reserved for future instructions)

**Comment by kasanovic** [comment]
@ubc-guy Please submit pull request with better text
