### ISSUE TITLE
What does the "M" means in OPMVV and OPMVX instructions?

### ISSUE THREAD

**Issue by Zissi-Lei** [riscv/riscv-v-spec#767]
Hi,
I want to known what does the "M" means in OPMVV and OPMVX instructions, thanks.

**Comment by jim-wilson** [comment]
I would guess multiply originally, since this is where most of the multiply/divide instructions are.  But ultimately the letter is meaningless, and never really had a specific meaning.  We just needed another letter other than I and F.  The only significant info here is that the OPI* instructions can take an immediate, and the OPM* instructions can't.

**Comment by aswaterman** [comment]
Indeed.

**Comment by ColsonZhang** [comment]
According to the content of the spec book, I think "M" means mask instructions.

**Comment by kasanovic** [comment]
mask
