### ISSUE TITLE
is vsetdcfg deprecated?

### ISSUE THREAD

**Issue by wanghuibin0** [riscv/riscv-v-spec#913]
I am reading materials about RVV.
In Chapter 4 of the book Computer Architecture, an instruction called vsetdcfg occurs in the example code. 
But I can't find description about vsetdcfg in this spec. 
Is it deprecated? Why?

**Comment by nick-knight** [comment]
The presentation in Computer Architecture, as well as The RISC-V Reader, concerns an early draft of the V-extension. The V-extension evolved considerably since then. You should treat the ISA spec as the definitive reference.

The functionality of vsetdcfg was largely folded into the vsetvl instructions.

**Comment by wanghuibin0** [comment]
Oh, I see. Thanks for reply.
